version: '2'
services:
  wp:
    image: stormerider/rancher-wordpress-nginx-trusty:v1.0.4.14
    environment:
      NEWRELIC_APPNAME: LongArmQuilting.ca
      WORDPRESS_AUTH_KEY: REDACTED
      WORDPRESS_AUTH_SALT: REDACTED
      WORDPRESS_DB_HOST: REDACTED
      WORDPRESS_DB_NAME: quilting_wp
      WORDPRESS_DB_PASS: REDACTED
      WORDPRESS_DB_PRFX: REDACTED
      WORDPRESS_DB_USER: longarmquilting
      WORDPRESS_LOGGED_IN_KEY: REDACTED
      WORDPRESS_LOGGED_IN_SALT: REDACTED
      WORDPRESS_NONCE_KEY: REDACTED
      WORDPRESS_NONCE_SALT: REDACTED
      WORDPRESS_PLUGINS: akismet,jetpack,nextgen-gallery,nginx-helper,wp-dbmanager
      WORDPRESS_SECURE_AUTH_KEY: REDACTED
      WORDPRESS_SECURE_AUTH_SALT: REDACTED
      WORDPRESS_THEMES: The_Hobbit_1_0_949,comet,scrappy,timeless,typominima
    volumes:
    - /home/rancher/efs/longarmquilting.ca/wp-content:/usr/share/nginx/www/wp-content
    - /home/rancher/newrelic.license:/newrelic.license
    ports:
    - 8008:80/tcp
    command:
    - /bin/bash
    - /start.sh
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: role=management
      io.rancher.scheduler.global: 'true'
