version: '2'
services:
  wpmu:
    image: stormerider/rancher-wpmu-nginx-trusty:v1.0.4.14
    environment:
      NEWRELIC_APPNAME: StormeRider.com
      WORDPRESS_AUTH_KEY: REDACTED
      WORDPRESS_AUTH_SALT: REDACTED
      WORDPRESS_DB_HOST: REDACTED
      WORDPRESS_DB_NAME: stormerider_wp
      WORDPRESS_DB_PASS: REDACTED
      WORDPRESS_DB_PRFX: REDACTED
      WORDPRESS_DB_USER: stormerider
      WORDPRESS_LOGGED_IN_KEY: REDACTED
      WORDPRESS_LOGGED_IN_SALT: REDACTED
      WORDPRESS_MU_DOM: stormerider.com
      WORDPRESS_NONCE_KEY: REDACTED
      WORDPRESS_NONCE_SALT: REDACTED
      WORDPRESS_PLUGINS: akismet,cloudflare-flexible-ssl,cryout-theme-settings,easy-automatic-newsletter,jetpack,nextgen-gallery,nextgen-gallery-custom-fields,nextgen-gallery-plus,nginx-helper,smart-youtube,wordfence,wordpress-backup-to-dropbox,wordpress-https,wordpress-importer,wordpress-mu-domain-mapping,wp-better-emails,wp-dbmanager,wp-lightboxJS,wp-mail-smtp,wp-syntax-download-extension
      WORDPRESS_SECURE_AUTH_KEY: REDACTED
      WORDPRESS_SECURE_AUTH_SALT: REDACTED
      WORDPRESS_THEMES: mcfire-20
    volumes:
    - /home/rancher/efs/stormerider.com/wp-content:/usr/share/nginx/www/wp-content
    - /home/rancher/efs/stormerider.com/images:/usr/share/nginx/www/images
    - /home/rancher/efs/stormerider.com/iconset:/usr/share/nginx/www/iconset
    - /home/rancher/efs/stormerider.com/misc:/usr/share/nginx/www/misc
    - /home/rancher/newrelic.license:/newrelic.license
    ports:
    - 8015:80/tcp
    command:
    - /bin/bash
    - /start.sh
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: role=management
      io.rancher.scheduler.global: 'true'
