version: '2'
services:
  wp:
    image: stormerider/rancher-wordpress-nginx-trusty:v1.0.4.14
    environment:
      NEWRELIC_APPNAME: CiaLeah.com
      WORDPRESS_AUTH_KEY: REDACTED
      WORDPRESS_AUTH_SALT: REDACTED
      WORDPRESS_DB_HOST: REDACTED
      WORDPRESS_DB_NAME: cialeah_wp
      WORDPRESS_DB_PASS: REDACTED
      WORDPRESS_DB_PRFX: REDACTED
      WORDPRESS_DB_USER: cialeah_wp
      WORDPRESS_LOGGED_IN_KEY: REDACTED
      WORDPRESS_LOGGED_IN_SALT: REDACTED
      WORDPRESS_NONCE_KEY: REDACTED
      WORDPRESS_NONCE_SALT: REDACTED
      WORDPRESS_PLUGINS: akismet,cloudflare-flexible-ssl,jetpack,nginx-helper,wordfence,wordpress-backup-to-dropbox,wordpress-https,wp-dbmanager,wp-mail-smtp
      WORDPRESS_SECURE_AUTH_KEY: REDACTED
      WORDPRESS_SECURE_AUTH_SALT: REDACTED
      WORDPRESS_THEMES: jeans
    volumes:
    - /home/rancher/efs/cialeah.com/wp-content:/usr/share/nginx/www/wp-content
    - /home/rancher/newrelic.license:/newrelic.license
    ports:
    - 8002:80/tcp
    command:
    - /bin/bash
    - /start.sh
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: role=management
      io.rancher.scheduler.global: 'true'
