version: '2'
services:
  nginx:
    scale: 3
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 20000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 80
      unhealthy_threshold: 5
      initializing_timeout: 600000
      interval: 2000
      strategy: recreateOnQuorum
      reinitializing_timeout: 600000
  extplorer:
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 20000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 8088
      unhealthy_threshold: 5
      initializing_timeout: 600000
      interval: 2000
      strategy: recreateOnQuorum
      reinitializing_timeout: 600000
